image: jainamjhaveri/gitlab-ci-android-fastlane

cache:
  paths:
    - .gradle/

before_script:
  - touch local.properties
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - build
#  - test
  - static analysis
#  - beta
#  - prod

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs

#unitTests:
#  stage: test
#  script:
#    - ./gradlew test
#
quality_assurance:
  stage: static analysis
  script:
    - ./gradlew lint
  artifacts:
    paths:
      - app/build/outputs/reports

#deploy_beta:
#  stage: beta
#  script:
#    - fastlane beta
#  only:
 #   - release
#  artifacts:
#    paths:
#      - app/build/outputs/apk/release


#deploy_prod:
#  stage: prod
#  script:
#    - fastlane playstore
#  only:
 #   - master